accountsservice
amd-ucode
awesome-terminal-fonts
base
bluedevil
bluez
bluez-libs
breeze-gtk
btrfs-progs
dolphin
dosfstools
efibootmgr
exfatprogs
ffmpegthumbnailer
ffmpegthumbs
grub
gst-libav
gst-plugin-pipewire
gst-plugin-va
gst-plugins-bad
gst-plugins-ugly
kde-gtk-config
kdegraphics-thumbnailers
kdeplasma-addons
konsole
krunner
kscreen
kwallet-pam
libgsf
linux-firmware
logrotate
mesa
mkinitcpio
networkmanager
noto-fonts
noto-fonts-emoji
opencl-mesa
perl
pipewire-alsa
pipewire-pulse
plasma-desktop
plasma-login-manager
plasma-nm
plasma-pa
plasma-thunderbolt
poppler-glib
power-profiles-daemon
powerdevil
python
sof-firmware
spectacle
sudo
upower
usbutils
vulkan-radeon
which
wireplumber
xdg-user-dirs
xdg-utils
fuse2
snapper
btrfs-assistant
snap-pac
grub-btrfs
nano
